### ISSUE TITLE
scaling results in zero(S)

### ISSUE THREAD

**Issue by NedaRR** [jcaude/MSEntropy#1]
Hi I'm using MSE() for my data. The results for scale 1 is alright, but I get a lot of Zero(s) in scales 2-9. 
Any idea what’s the problem and how to fix it?

r_list <- seq(from = 0.1, to = 0.7, by = 0.05)
scales <- (1:10)
m<- 2

write_entropy <- function(input_csv, output_dir, r_list) {
    # Do not transpose
    df <- read.csv(input_csv, header = FALSE)
    out <- 
      map_dfr(df, ~{
        # Loop over columns
        map(r_list, function(r){
          # Loop over R values
          mse = MSE(.x, m = m, r = r , scales = scales)
          names(mse) <- sprintf("entropy_m2_r%s_s%s",r,seq(scales))
          mse
      }) %>% 
          unlist() %>% 
          bind_rows()
})
    write.csv(out, paste0(output_dir, "/", basename(input_csv)), row.names = FALSE)
}

 lapply(list_400, write_entropy, output_dir = "~/Documents/sample_entropy/MSE/test4", r_list = r_list)

**Comment by jcaude** [comment]
Hello,

First... take care, because this is a really alpha code that I don't really have the time (at the moment) to review/fix/develop.. Anyway, if you have too many zero(s) you can increase the similarity tolerance factor (parameter 'r') it should fix your problem.

jC

**Comment by NedaRR** [comment]
Thanks! I was looking at a range of r, and multiple m, but problem was there. Hope you can develop it further, though for now I'm suing another package.

**Comment by jcaude** [comment]
Yes, I bet there is more robust package than this one.. but thx to give it a try. You could also look in the litterature for more robust methods than MSE (for example iMSE, doi:10.3390/e20040212) that has some known limitations (eg non-stationary signal)
